# fly.toml app configuration file generated for pixelpanic on 2026-07-24T13:20:13+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pixelpanic'
primary_region = 'iad'

[build]
[env]
  DB_PATH = '/data/pixelpanic.sqlite'
  PORT = '3001'

[[mounts]]
  source = 'pixelpanic_data'
  destination = '/data'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
